dist: xenial

language: node_js

node_js:
  - node

addons:
  chrome: stable

script:
  - npm run build -- @yeiniel/ngrx-auth0
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox