dist: trusty
sudo: false

language: node_js

node_js:
  - node

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox