language: node_js

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox